# Generated by Django 2.0.4 on 2018-04-22 16:23

import archivo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivador',
            fields=[
                ('id_archivador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.SlugField(max_length=32, unique=True)),
                ('n_docs', models.IntegerField(default=0)),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_modificacion', models.DateTimeField(auto_now=True)),
                ('f_acceso', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('archivo', models.FileField(upload_to=archivo.models.get_upload_dir)),
                ('n_paginas', models.PositiveIntegerField(default=0)),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_modificacion', models.DateTimeField(auto_now=True)),
                ('f_acceso', models.DateTimeField()),
                ('archivador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='archivo.Archivador')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id_etiqueta', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.SlugField(max_length=48, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='etiquetas',
            field=models.ManyToManyField(to='archivo.Etiqueta'),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('archivador', 'nombre')},
        ),
    ]
