# Generated by Django 2.0.4 on 2018-04-22 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivador',
            name='f_acceso',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='documento',
            name='f_acceso',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
