# Generated by Django 2.0.4 on 2018-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivo', '0003_auto_20180422_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='n_paginas',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
