# Generated by Django 2.0.5 on 2018-05-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivo', '0004_auto_20180422_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivador',
            options={'verbose_name': 'Archivador', 'verbose_name_plural': 'Archivadores'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'documento', 'verbose_name_plural': 'documentos'},
        ),
    ]
